Add hostname to the default schema
This will allow it to show in Arcadia. Before this it would still work
as a dynamic field.

This change also required setting the __version__ field to be
non-multi-valued. Something changed the default when I added hostname I
guess. Without this change this error shows:

java.lang.Exception: {responseHeader={status=0,QTime=1511},failure={null=org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException:Error CREATEing SolrCore 'd14d7_shard1_replica1': Unable to create core [d14d7_shard1_replica1] Caused by: _version_ field must exist in schema, using indexed="true" or docValues="true", stored="true" and multiValued="false" (_version_ is multiValued}}